version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    environment:
      NODE_ENV: development

  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: production
    depends_on:
      - backend
